[package]
name = "radkit"
version = "0.0.2"
edition = "2024"
license= "Apache-2.0"
description = "Rust AI Agent Development Kit"
repository = "https://github.com/microagents/radkit"
homepage = "https://radkit.dev"
documentation = "https://radkit.dev"
keywords = ["ai", "agent", "ai-agent", "a2a", "agent-sdk"]
readme = "README.md"

[dependencies]
a2a-types = { path = "../a2a-types", version = "0.1.1" }
tokio = { version = "1.47", features = ["full"] }
async-trait = "0.1.88"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
reqwest = { version = "0.12.23", features = ["json", "stream"] }
thiserror = "2.0.14"
tracing = "0.1.41"
futures = "0.3.31"
tokio-stream = { version = "0.1.17", features = ["io-util"] }
tokio-util = { version = "0.7", features = ["io", "codec"] }
uuid = { version = "1.18.0", features = ["v4", "serde"] }
chrono = { version = "0.4.41", features = ["serde"] }
dashmap = "6.1.0"
rmcp = { version = "0.6.3", features = ["client", "transport-child-process", "transport-streamable-http-client-reqwest"] }

# Observability dependencies
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "json", "registry", "fmt"] }
tracing-opentelemetry = "0.23.0"
opentelemetry = "0.22.0"
opentelemetry_sdk = { version = "0.22.1", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.15.0", features = ["tokio", "grpc-tonic", "http-proto"] }
opentelemetry-semantic-conventions = "0.14.0"
opentelemetry-stdout = { version = "0.3.0", features = ["trace"] }
tonic = "0.11"
sha2 = "0.10"
regex = "1.10"
once_cell = "1.19"

[dev-dependencies]
dotenvy = "0.15"
